### ISSUE TITLE
Cambiar politica de cancelación de clases

### ISSUE THREAD

**Issue by 56kz** [56kz/Thesitedjschedule#13]
Que el usuario no pueda cancelar una clase justo a la hora. ejemplo entrar a las 5 55 y cancelar la clae de hoe de 4 a 6 , qhue se pueda cancelar 1 hora antes, o sin comuniquese con el profe,

**Comment by 56kz** [comment]
No puedes eliminar esta clase, comunicate con tu profe

**Comment by andres-soto-h** [comment]
Se implementa restricción para que no sea posible cancelar una clase con menos de una hora de antelación.
