### ISSUE TITLE
Aumentar velocidad de carga de la app

### ISSUE THREAD

**Issue by 56kz** [56kz/Thesitedjschedule#15]
Soto man es el master y sabe cómo se hace , creo que ya lo hizo , pero confirmar...

**Comment by andres-soto-h** [comment]
Se cambia toda la lógica para programar y cancelar clases hacia el backend. Ahora desde el navegador solo se hacen peticiones ajax y el servidor responde con un código de éxito o error, así se evita tener que cargar nuevamente toda la lista completa de eventos; únicamente añade o elimina el evento en cuestión.
