### ISSUE TITLE
Mantener el footer siempre abajo de la pagina 

### ISSUE THREAD

**Issue by 56kz** [56kz/Thesitedjschedule#23]
Hay vistas en la que el footes aparece en la parte inferior del todo , pero en algunas que se recorta y aparece mas arriba, la idea es encontrar una propiedad que la mantenga siemre abajo de la pantalla , si existe se modifica , de lo contrario dejar asi ome veci

**Comment by andres-soto-h** [comment]
Se corrige el footer en el login y en la pagina de inicio. 

Se deshabilito de las demás vistas, si es necesario mostrarlo en todas las vistas, se debe crear un partial con el footer e inscrustrarlo en cada vista, también se puede incluir de forma manual.
